name: micro-ci-test
namespace: "{{ .namespace }}"
registry:
  type: consul
  address: "micro-ci-test-consul"
  port: 8500
  useSSL: false
variables:
  namespace: test.micro-ci
  v2: v2-value
commonEnvs:
  MICRO_SERVER_VERSION: v0.0.1
  MICRO_SERVER_ID: default
  MICRO_REGISTER_INTERVAL: "30"
  MICRO_REGISTER_TTL: "60"
thirdServices:
  consul:
    image:
      name: consul:latest
      ref: docker.io/library/consul
    exposedPorts:
      8500/tcp:
        hostIP: 127.0.0.1
        hostPort: 8501
    assertions:
      successes:
        - Consul agent running!
  micro-ci-api:
    dependsOn:
      - consul
    image:
      name: alydnh/micro:latest
    exposedPorts:
      8089/tcp:
        hostIP: 0.0.0.0
        hostPort: 7089
    args:
      - --api_address=0.0.0.0:8089
      - api
      - --handler=rpc
      - --namespace={{ .namespace }}.ci
    assertions:
      successes:
        - HTTP API Listening on
      fails:
        - Error listing endpoints
        - micro - A microservice toolkit
        - Incorrect Usage.
services:
  helloWorld:
    dependsOn:
      - consul
    build:
      git: https://github.com/alydnh/helloworld
      branch: master
      target: target
      env:
        GOOS: linux
      scripts:
        - go build -o target/main -v -mod=vendor main.go
    image:
      name: dockerio/alydnh/helloworld:v1.0.0
      dockerFile: |
        FROM docker.srgow.com/golang:stretch
        ADD ./main /main
        WORKDIR /
        RUN chmod u+x /main
        CMD ["/main","--port","8090","--host","0.0.0.0"]
    assertions:
      successes:
        - hello world